name: Build And Push Docker image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.mauriziocarella.it
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          #platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          tags: |
            registry.mauriziocarella.it/mauriziocarella.it:latest
            registry.mauriziocarella.it/mauriziocarella.it:${{ github.ref_name }}
          build-args: |
            APP_VERSION=${{ github.ref_name }}

  update:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Trigger deployment via HTTP callback
        run: |
          curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER_HTTP_API_TOKEN }}" "https://registry.mauriziocarella.it/update?image=registry.mauriziocarella.it/mauriziocarella.it"
